version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    container_name: brighted_db
    environment:
      POSTGRES_USER: ihsan
      POSTGRES_PASSWORD: ihsanroot
      POSTGRES_DB: brighted_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  app:
    build: .
    container_name: backend_brighted_app
    depends_on:
      - db
    ports: 
      - "3000:3000"
    env_file:
      - .env
    
  nginx:
    image: nginx:alpine
    container_name: nginx_brighted_app
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app

volumes:
  pgdata: